const cloud = require('wx-server-sdk')

cloud.init({
  env: cloud.DYNAMIC_CURRENT_ENV,
})

const db = cloud.database()

// 地形数据
const terrainData = [
  {
    id: 1,
    name: '山地',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+mountain+landscape+watercolor+cartoon+style+snow+peaks+blue+sky+eagle+flying+goat+marmot+wildflowers&image_size=square_hd',
    features: '高耸陡峭，海拔高，山峦起伏连绵不断',
    climate: '气候随海拔变化，山顶寒冷，山下温暖',
    vegetation: '从山脚到山顶植被逐渐变化，多为针叶林和草甸',
    region: '喜马拉雅山、天山、昆仑山、秦岭',
    summary: '大地的脊梁，是许多珍稀动植物的家园',
  },
  {
    id: 2,
    name: '平原',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+vast+green+plain+landscape+watercolor+cartoon+style+farmland+river+village+blue+sky&image_size=square_hd',
    features: '地势平坦开阔，土地肥沃，视野辽阔',
    climate: '温和湿润，四季分明，适合农耕',
    vegetation: '农田密布，庄稼茂盛，稻浪滚滚',
    region: '东北平原、华北平原、长江中下游平原',
    summary: '孕育中华文明的肥沃土地，是粮食的主要产地',
  },
  {
    id: 3,
    name: '盆地',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+basin+landscape+watercolor+cartoon+style+surrounded+mountains+warm+colors+village+river&image_size=square_hd',
    features: '四周高、中间低，像一个大盆子',
    climate: '温暖湿润，少风沙，云雾多',
    vegetation: '亚热带植物丰富，竹林茂密',
    region: '四川盆地、塔里木盆地、柴达木盆地、准噶尔盆地',
    summary: '群山环抱的天府之国，物产丰富气候宜人',
  },
  {
    id: 4,
    name: '高原',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+high+plateau+landscape+watercolor+cartoon+style+grassland+blue+sky+yaks+distant+mountains&image_size=square_hd',
    features: '海拔高，面积大，地面开阔辽阔',
    climate: '气候寒冷，日照充足，紫外线强',
    vegetation: '草原广阔，高山草甸，油菜花田',
    region: '青藏高原、内蒙古高原、黄土高原、云贵高原',
    summary: '离天空最近的地方，有壮美的草原和圣洁的雪山',
  },
  {
    id: 5,
    name: '丘陵',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+rolling+hills+landscape+watercolor+cartoon+style+tea+plantations+terraced+fields+misty+mountains&image_size=square_hd',
    features: '地势起伏和缓，坡度较小，连绵不断',
    climate: '温暖湿润，雨量充沛，云雾缭绕',
    vegetation: '茶树、果树遍布，森林覆盖率高',
    region: '东南丘陵、山东丘陵、辽东丘陵',
    summary: '层峦叠翠的绿色海洋，茶叶和水果的故乡',
  },
  {
    id: 6,
    name: '沙漠',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+desert+landscape+watercolor+cartoon+style+sand+dunes+camel+cactus+sunset+warm+colors&image_size=square_hd',
    features: '沙石广布，干旱少雨，昼夜温差极大',
    climate: '干燥炎热，降水稀少，风沙大',
    vegetation: '仙人掌、骆驼刺、胡杨等耐旱植物',
    region: '塔克拉玛干沙漠、戈壁滩、巴丹吉林沙漠',
    summary: '神秘的金色海洋，藏着顽强的生命奇迹',
  },
  {
    id: 7,
    name: '喀斯特地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+karst+landscape+watercolor+cartoon+style+limestone+peaks+caves+underground+river+green+vegetation&image_size=square_hd',
    features: '石灰岩广布，多溶洞、石林、地下河',
    climate: '温暖湿润，雨水充沛，溶蚀作用强',
    vegetation: '喜钙植物丰富，藤蔓缠绕，绿意盎然',
    region: '广西桂林、贵州荔波、云南石林、重庆武隆',
    summary: '大自然的雕塑公园，山水甲天下的人间仙境',
  },
  {
    id: 8,
    name: '丹霞地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+red+rock+landscape+watercolor+cartoon+style+red+cliffs+layered+mountains+blue+sky&image_size=square_hd',
    features: '红色砂砾岩构成，顶平身陡，色彩斑斓',
    climate: '温暖湿润，风化侵蚀强烈',
    vegetation: '崖壁植被稀疏，山顶和谷底植被茂密',
    region: '广东丹霞山、福建武夷山、甘肃张掖、贵州赤水',
    summary: '如霞似火的彩色山峦，大自然的调色盘',
  },
  {
    id: 9,
    name: '雅丹地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+yadan+landscape+watercolor+cartoon+style+wind+eroded+rock+formations+desert+sunset+dry+lake&image_size=square_hd',
    features: '风力侵蚀形成，怪石嶙峋，千姿百态',
    climate: '极度干旱，风大沙多，昼夜温差大',
    vegetation: '植被极其稀少，几乎寸草不生',
    region: '新疆罗布泊、甘肃敦煌魔鬼城、柴达木盆地',
    summary: '风的杰作，戈壁滩上的魔幻城堡',
  },
  {
    id: 10,
    name: '黄土地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+loess+plateau+landscape+watercolor+cartoon+style+yellow+soil+terraces+cave+houses+sheep&image_size=square_hd',
    features: '黄土深厚，千沟万壑，支离破碎',
    climate: '温带大陆性气候，降水集中多暴雨',
    vegetation: '草原和落叶阔叶林，植被覆盖率较低',
    region: '黄土高原、山西、陕西、甘肃东部',
    summary: '中华文明的摇篮，独特的黄土文化发源地',
  },
  {
    id: 11,
    name: '峡谷',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+deep+canyon+landscape+watercolor+cartoon+style+steep+cliffs+river+flowing+through+rainbow+bridge&image_size=square_hd',
    features: '两岸峭壁高耸，河道深切，气势磅礴',
    climate: '垂直气候差异明显，谷底湿润，山顶寒冷',
    vegetation: '从热带到寒带植被垂直分布，种类丰富',
    region: '长江三峡、雅鲁藏布大峡谷、虎跳峡、泸沽湖大峡谷',
    summary: '地球最美丽的伤痕，壮美与险峻并存',
  },
  {
    id: 12,
    name: '海岸地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+coastal+landscape+watercolor+cartoon+style+beach+rocks+waves+seagulls+shells+blue+sea&image_size=square_hd',
    features: '海陆交汇，沙滩、礁石、海蚀洞交错分布',
    climate: '海洋性气候，冬暖夏凉，潮湿多风',
    vegetation: '红树林、海草床、耐盐植物',
    region: '海南三亚、福建厦门、山东青岛、广西北海',
    summary: '大海与陆地的浪漫邂逅，生机勃勃的蓝色边疆',
  },
  {
    id: 13,
    name: '沼泽湿地',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+wetland+marsh+landscape+watercolor+cartoon+style+reeds+lotus+ducks+herons+calm+water+sunset&image_size=square_hd',
    features: '地势低洼，常年积水，水草丰美',
    climate: '湿润多雨，雾气重，气候温和',
    vegetation: '芦苇、香蒲、睡莲等水生植物茂密',
    region: '三江平原湿地、青海湖、鄱阳湖、扎龙湿地',
    summary: '地球之肾，是鸟类和水生动物的天堂',
  },
  {
    id: 14,
    name: '冰川地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+glacier+landscape+watercolor+cartoon+style+ice+peaks+blue+glacier+lake+snow+mountains+crystal&image_size=square_hd',
    features: '冰川覆盖，冰峰林立，蓝冰剔透',
    climate: '终年严寒，冰雪不化，氧气稀薄',
    vegetation: '植被极少，只有地衣和苔藓等低等植物',
    region: '喜马拉雅山冰川、天山冰川、祁连山冰川',
    summary: '固态水的宝库，是大江大河的源头',
  },
  {
    id: 15,
    name: '冻土地貌',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+tundra+permafrost+landscape+watercolor+cartoon+style+moss+lichens+reindeer+low+shrubs+aurora&image_size=square_hd',
    features: '地下常年冰冻，夏天表层融化，地面凹凸不平',
    climate: '冬季漫长严寒，夏季短暂凉爽',
    vegetation: '地衣、苔藓、低矮灌木，没有高大树木',
    region: '青藏高原多年冻土区、大兴安岭北部',
    summary: '冻土层是地球的天然冰箱，藏着远古的秘密',
  },
  {
    id: 16,
    name: '岛屿',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+tropical+island+landscape+watercolor+cartoon+style+palm+trees+turquoise+sea+coral+reef+white+sand&image_size=square_hd',
    features: '四面环海，面积大小不一，海岸线曲折',
    climate: '海洋性气候，温暖湿润，多台风',
    vegetation: '热带亚热带植物丰富，椰子树、棕榈树常见',
    region: '台湾岛、海南岛、崇明岛、西沙群岛',
    summary: '散落在大海上的明珠，每一个都有独特的风情',
  },
  {
    id: 17,
    name: '草原',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+grassland+steppe+landscape+watercolor+cartoon+style+endless+grass+horses+sheep+yurt+blue+sky+clouds&image_size=square_hd',
    features: '地势平坦开阔，以草本植物为主，一望无际',
    climate: '温带大陆性气候，降水较少，昼夜温差大',
    vegetation: '针茅、羊草等多年生草本植物',
    region: '内蒙古草原、呼伦贝尔草原、锡林郭勒草原',
    summary: '天苍苍野茫茫，风吹草低见牛羊的壮丽画卷',
  },
  {
    id: 18,
    name: '森林',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+forest+landscape+watercolor+cartoon+style+tall+trees+sunlight+deer+squirrel+mushroom+stream&image_size=square_hd',
    features: '树木茂密覆盖，生物多样性丰富',
    climate: '湿润多雨，冬暖夏凉，气候宜人',
    vegetation: '乔木、灌木、草本植物层层叠叠',
    region: '东北林区、西南林区、东南丘陵林区',
    summary: '地球之肺，是千千万万野生动植物的家园',
  },
]

// 气候数据
const climateData = [
  {
    id: 1,
    name: '温带季风气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+temperate+monsoon+landscape+watercolor+cartoon+style+four+seasons+trees+spring+blossom+summer+green+autumn+yellow+winter+snow&image_size=square_hd',
    temperature: '四季分明，春暖夏热，秋凉冬冷',
    precipitation: '夏季多雨，冬季干燥，雨热同期',
    characteristics: '季风显著，春天花开，夏天炎热多雨，秋天凉爽，冬天寒冷',
    region: '中国东北、华北、朝鲜半岛、日本北部',
    summary: '春夏秋冬轮番上阵，是大自然最美丽的四季舞台',
  },
  {
    id: 2,
    name: '亚热带季风气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+subtropical+monsoon+landscape+watercolor+cartoon+style+lush+green+bamboo+rain+paddy+fields+lotus+pond&image_size=square_hd',
    temperature: '夏季高温，冬季温和，四季常青',
    precipitation: '雨水丰沛，夏季梅雨绵绵，台风带来暴雨',
    characteristics: '温暖湿润，植被常绿，梅雨和台风是特色',
    region: '中国华东、华南、长江中下游、台湾',
    summary: '绿意盎然的鱼米之乡，雨水滋润万物生长',
  },
  {
    id: 3,
    name: '热带季风气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+tropical+monsoon+landscape+watercolor+cartoon+style+coconut+palm+beach+monkey+colorful+birds+bright+sun&image_size=square_hd',
    temperature: '全年高温，长夏无冬，阳光充足',
    precipitation: '分旱雨两季，雨季暴雨倾盆，旱季阳光灿烂',
    characteristics: '阳光充足，植物常绿，水果丰富，海风习习',
    region: '中国海南、云南南部、印度、泰国、越南',
    summary: '阳光与雨林的家园，一年四季都是夏天',
  },
  {
    id: 4,
    name: '温带大陆性气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+temperate+continental+landscape+watercolor+cartoon+style+vast+grassland+sheep+yurt+blue+sky+white+clouds&image_size=square_hd',
    temperature: '冬冷夏热，昼夜温差大，四季分明',
    precipitation: '降水稀少，集中在夏季，气候干燥',
    characteristics: '大陆性强，草原辽阔，风沙大，天空特别蓝',
    region: '中国西北、蒙古、中亚、西伯利亚南部',
    summary: '辽阔的草原与沙漠，蓝天白云下的壮美天地',
  },
  {
    id: 5,
    name: '高原山地气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+high+mountain+plateau+climate+landscape+watercolor+cartoon+style+bright+sun+thin+air+yaks+tents+snow+peaks&image_size=square_hd',
    temperature: '气温低，日夜温差大，太阳辐射强',
    precipitation: '降水少，空气稀薄干燥，多降雪',
    characteristics: '阳光强烈，紫外线强，氧气稀薄，风大寒冷',
    region: '青藏高原、帕米尔高原、安第斯山脉',
    summary: '离太阳最近的天空，雪山与草原的圣洁世界',
  },
  {
    id: 6,
    name: '寒温带气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+cold+temperate+landscape+watercolor+cartoon+style+snow+forest+pine+trees+reindeer+aurora+borealis+blue+tone&image_size=square_hd',
    temperature: '冬季漫长严寒，夏季短暂凉爽',
    precipitation: '降水不多，以雪为主，积雪深厚',
    characteristics: '冰雪覆盖，针叶林茂密，动物多有厚皮毛',
    region: '中国大兴安岭北段、西伯利亚、北欧北部',
    summary: '冰雪精灵的故乡，银装素裹的童话世界',
  },
  {
    id: 7,
    name: '热带雨林气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+tropical+rainforest+landscape+watercolor+cartoon+style+dense+jungle+parrot+toucan+waterfall+lianas+bright+green&image_size=square_hd',
    temperature: '全年高温多雨，温差极小',
    precipitation: '雨水极多，几乎每天都会下一场雨',
    characteristics: '植物层层叠叠，动物种类繁多，空气湿润',
    region: '亚马逊平原、刚果盆地、东南亚群岛',
    summary: '地球之肺，生物种类最丰富的绿色宝库',
  },
  {
    id: 8,
    name: '地中海气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+mediterranean+climate+landscape+watercolor+cartoon+style+olive+trees+vineyard+blue+sea+white+houses+lavender&image_size=square_hd',
    temperature: '夏季炎热干燥，冬季温和多雨',
    precipitation: '冬雨夏干，降水集中在冬季',
    characteristics: '阳光充足，橄榄和葡萄长得好，海风宜人',
    region: '地中海沿岸、加州、智利中部、南非开普敦',
    summary: '阳光、大海与薰衣草，度假胜地的完美气候',
  },
  {
    id: 9,
    name: '温带海洋性气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+temperate+oceanic+climate+landscape+watercolor+cartoon+style+green+meadows+sheep+castle+mist+rainbow+gentle+hills&image_size=square_hd',
    temperature: '冬暖夏凉，全年温和，温差很小',
    precipitation: '全年湿润，细雨绵绵，云雾多',
    characteristics: '温和湿润，牧草丰美，适合畜牧业',
    region: '西欧、英国、爱尔兰、新西兰',
    summary: '温柔如诗的气候，绿色草原与古堡的童话世界',
  },
  {
    id: 10,
    name: '极地气候',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+polar+climate+landscape+watercolor+cartoon+style+ice+snow+polar+bear+penguin+igloo+aurora+blue+white&image_size=square_hd',
    temperature: '全年酷寒，冰雪覆盖，寒风刺骨',
    precipitation: '降水极少，干燥寒冷，多暴风雪',
    characteristics: '极昼极夜，冰川广布，动物耐寒能力极强',
    region: '南极洲、北极圈内、格陵兰岛',
    summary: '冰雪世界的尽头，勇敢生命的极限挑战',
  },
]

// 地区数据
const regionData = [
  {
    id: 1,
    name: '东北地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+northeast+china+landscape+watercolor+cartoon+style+snowy+forests+mountains+tiger+deer+pine+trees&image_size=square_hd',
    features: '山高谷深，森林茂密，林海雪原壮丽辽阔',
    climate: '冬季严寒漫长，夏季温凉短促，积雪期长',
    vegetation: '针叶林、针阔混交林广布，白桦、红松、落叶松茂密',
    region: '黑龙江、吉林、辽宁及内蒙古东部',
    summary: '林海雪原的壮美大地，是东北虎和梅花鹿的家园',
  },
  {
    id: 2,
    name: '华北地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+north+china+plain+landscape+watercolor+cartoon+style+great+wall+rolling+hills+ancient+temple+cherry+blossoms&image_size=square_hd',
    features: '平原广阔，历史悠久，文化灿烂，人杰地灵',
    climate: '四季分明，冬季寒冷干燥，夏季炎热多雨',
    vegetation: '落叶阔叶林为主，槐树、杨树、柳树常见',
    region: '北京、天津、河北、山西、内蒙古中部',
    summary: '中华文明的重要发祥地，承载着千年的历史与传奇',
  },
  {
    id: 3,
    name: '西北地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+northwest+china+landscape+watercolor+cartoon+style+sand+dunes+camel+oasis+desert+sunset+red+cliffs&image_size=square_hd',
    features: '大漠孤烟，长河落日，风光壮美，戈壁辽阔',
    climate: '干旱少雨，昼夜温差极大，日照充足',
    vegetation: '耐旱植物为主，胡杨、骆驼刺、仙人掌、红柳',
    region: '陕西、甘肃、青海、宁夏、新疆',
    summary: '神秘壮阔的丝绸之路，沙漠中的绿洲藏着生命的奇迹',
  },
  {
    id: 4,
    name: '西南地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+southwest+china+landscape+watercolor+cartoon+style+high+mountains+cloud+forest+panda+bamboo+monkey&image_size=square_hd',
    features: '高山连绵，雨林茂密，动物众多，风景如画',
    climate: '气候垂直差异显著，湿润多雨，云雾缭绕',
    vegetation: '热带雨林、亚热带常绿阔叶林、高山草甸',
    region: '四川、云南、贵州、西藏、重庆',
    summary: '大自然的珍稀宝库，是大熊猫和金丝猴的美丽故乡',
  },
  {
    id: 5,
    name: '华南地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+south+china+landscape+watercolor+cartoon+style+tropical+rainforest+elephant+peacock+blue+sea+palm+trees&image_size=square_hd',
    features: '热带雨林，四季如春，物种丰富，风光旖旎',
    climate: '温暖湿润，夏长冬短，雨量充沛',
    vegetation: '热带季雨林、常绿阔叶林，榕树、木棉、椰树繁茂',
    region: '广东、广西、海南、香港、澳门',
    summary: '四季花开的热带天堂，充满生机与活力的绿色世界',
  },
  {
    id: 6,
    name: '华中地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+central+china+landscape+watercolor+cartoon+style+lakes+rivers+farmland+fisht+rice+paddies+lotus&image_size=square_hd',
    features: '湖泊众多，大河纵横，鱼米之乡，物产丰富',
    climate: '温暖湿润，四季分明，雨水充沛',
    vegetation: '水稻田、莲塘密布，杨树、柳树、樟树常见',
    region: '河南、湖北、湖南',
    summary: '千湖之省的鱼米之乡，是江豚和白鳍豚的珍贵家园',
  },
  {
    id: 7,
    name: '华东地区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute+east+china+landscape+watercolor+cartoon+style+water+towns+green+hills+tea+plantations+crane+bamboo&image_size=square_hd',
    features: '水乡泽国，物产丰富，经济发达，文化繁荣',
    climate: '温暖湿润，四季分明，梅雨季节明显',
    vegetation: '亚热带常绿阔叶林，茶园、竹林、水杉遍布',
    region: '上海、江苏、浙江、安徽、福建、江西、山东、台湾',
    summary: '烟雨江南的诗意水乡，丹顶鹤翩翩起舞的美丽家园',
  },
]

// 动物数据
const animalData = [
  {
    id: 1,
    name: '羊驼',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/alpaca.png',
    habitat: '生活在南美洲安第斯山脉的高原草地上',
    food: '主要吃牧草和干草，偶尔也吃些谷物',
    habits: '性格温顺爱撒娇，不高兴时会朝人吐口水',
    secret: '羊驼的毛又软又暖，一年能剪下好几斤毛呢',
    protectionLevel: '家养动物',
  },
  {
    id: 2,
    name: '獾',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/badger.png',
    habitat: '喜欢在森林和草地里挖洞居住',
    food: '什么都吃，蚯蚓、昆虫、坚果和野果都爱',
    habits: '昼伏夜出，白天躲在洞里呼呼大睡',
    secret: '獾的爪子力气超大，挖洞速度快得像小铲车',
    protectionLevel: '无危',
  },
  {
    id: 3,
    name: '熊',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/bear.png',
    habitat: '生活在森林和山地，从寒带到温带都有它的身影',
    food: '喜欢吃浆果、鱼和蜂蜜，也吃嫩草和昆虫',
    habits: '冬天来临前拼命进食，然后找个洞穴呼呼冬眠',
    secret: '熊的嗅觉非常灵敏，能闻到几公里外的食物',
    protectionLevel: '无危',
  },
  {
    id: 4,
    name: '海狸',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/beaver.png',
    habitat: '生活在河流和湖泊边，是天生的建筑师',
    food: '主要啃食树皮、树枝和水生植物',
    habits: '用树枝和泥巴筑水坝，把家安在池塘中央',
    secret: '海狸的门牙一直在生长，所以要不停啃木头磨牙',
    protectionLevel: '无危',
  },
  {
    id: 5,
    name: '蜜蜂',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/bee.png',
    habitat: '生活在蜂巢里，蜂巢常筑在树洞或蜂箱中',
    food: '采集花蜜和花粉作为食物',
    habits: '分工明确，蜂后产卵，工蜂采蜜筑巢',
    secret: '蜜蜂会跳“8字舞”，是在告诉同伴哪里有花蜜哦',
    protectionLevel: '无危',
  },
  {
    id: 6,
    name: '金丝雀',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/canary.png',
    habitat: '原产于大西洋加那利群岛，如今多被当作宠物饲养',
    food: '喜欢吃谷物种子和新鲜蔬菜',
    habits: '歌声婉转动听，公鸟常常引吭高歌',
    secret: '金丝雀曾被矿工带入矿井，用来提前预警有毒气体',
    protectionLevel: '家养动物',
  },
  {
    id: 7,
    name: '猫',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/cat_v2.png',
    habitat: '与人类共同生活，几乎遍布世界各地',
    food: '主要吃肉类，是天生的肉食动物',
    habits: '喜欢独处，白天睡觉多，夜晚视力超好',
    secret: '猫的胡须能感知周围空间，帮助它判断能否通过缝隙',
    protectionLevel: '家养动物',
  },
  {
    id: 8,
    name: '牛',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/cow.png',
    habitat: '生活在牧场和农场，是人类重要的家畜',
    food: '主要吃青草和干草',
    habits: '喜欢反刍，吃下的草会反复咀嚼消化',
    secret: '牛有四个胃，帮助它把粗糙的草消化得干干净净',
    protectionLevel: '家养动物',
  },
  {
    id: 9,
    name: '鹤',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/crane.png',
    habitat: '栖息在湿地、沼泽和河流附近',
    food: '喜欢吃鱼虾、昆虫和水生植物',
    habits: '常常成群迁徙，飞行时排成整齐的队形',
    secret: '鹤在中国传统文化里象征长寿和吉祥',
    protectionLevel: '无危',
  },
  {
    id: 10,
    name: '乌鸦',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/crow.png',
    habitat: '适应力极强，森林、城市里都能看到它',
    food: '什么都吃，果实、昆虫、腐肉都不挑剔',
    habits: '非常聪明，会用工具解决问题',
    secret: '乌鸦能记住人的脸，还会互相传递“陌生人”的消息',
    protectionLevel: '无危',
  },
  {
    id: 11,
    name: '狗',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/dog_v2.png',
    habitat: '是人类最早驯化的动物，陪伴人类生活在世界各地',
    food: '主要吃肉类和狗粮，也能吃些蔬菜',
    habits: '忠诚友善，喜欢和主人玩耍散步',
    secret: '狗的嗅觉比人类灵敏上万倍，是天生的“侦探”',
    protectionLevel: '家养动物',
  },
  {
    id: 12,
    name: '海豚',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/dolphin.png',
    habitat: '生活在温暖的海洋和部分河流中',
    food: '主要吃鱼类和乌贼',
    habits: '喜欢群居，常常跃出水面嬉戏玩耍',
    secret: '海豚靠回声定位捕猎，就像自带“声呐”一样',
    protectionLevel: '无危',
  },
  {
    id: 13,
    name: '鸭',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/duck.png',
    habitat: '喜欢生活在池塘、湖泊和河流附近',
    food: '喜欢吃水草、小鱼虾和昆虫',
    habits: '擅长游泳，脚上有蹼像小船桨',
    secret: '鸭子的羽毛表面有油脂，下水也不会被打湿',
    protectionLevel: '无危',
  },
  {
    id: 14,
    name: '鹰',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/eagle.png',
    habitat: '栖息在高山悬崖和开阔的天空',
    food: '主要捕食小型哺乳动物、鱼类和鸟类',
    habits: '视力超强，喜欢在高空盘旋寻找猎物',
    secret: '老鹰的眼睛比人类锐利八倍，能看清很远的猎物',
    protectionLevel: '无危',
  },
  {
    id: 15,
    name: '大象',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/elephant.png',
    habitat: '生活在非洲草原和亚洲的热带丛林中',
    food: '每天要吃上百公斤的树叶、树皮和野草',
    habits: '家族观念很强，由年长的母象带领象群',
    secret: '大象的鼻子有四万多块肌肉，能卷树枝也能喝水',
    protectionLevel: '濒危',
  },
  {
    id: 16,
    name: '麋鹿',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/elk.png',
    habitat: '曾一度野外灭绝，如今在江苏大丰、湖北石首等保护区重引入定居',
    food: '喜欢吃青草、树叶和嫩枝',
    habits: '喜欢在水边活动，善于游泳，秋季雄鹿会争偶',
    secret: '麋鹿又叫"四不像"——角像鹿、脸像马、蹄像牛、尾像驴，曾一度野外灭绝，靠人工繁育重新回归',
    protectionLevel: '野外灭绝',
  },
  {
    id: 17,
    name: '狐狸',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/fox.png',
    habitat: '适应力很强，森林、草原、甚至城市郊区都能生活',
    food: '喜欢吃小型啮齿动物、鸟类和野果',
    habits: '机警聪明，行动敏捷，常常独自捕猎',
    secret: '狐狸的尾巴又大又蓬松，冬天睡觉时能当围巾保暖',
    protectionLevel: '无危',
  },
  {
    id: 18,
    name: '青蛙',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/frog.png',
    habitat: '生活在池塘、稻田和潮湿的草丛里',
    food: '主要捕食昆虫和小型无脊椎动物',
    habits: '会冬眠，用皮肤和肺一起呼吸',
    secret: '青蛙的舌头又长又粘，捕虫速度快到眨眼就完成',
    protectionLevel: '无危',
  },
  {
    id: 19,
    name: '长颈鹿',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/giraffe.png',
    habitat: '生活在非洲的热带草原上',
    food: '喜欢吃金合欢树顶端的嫩叶',
    habits: '长长的脖子方便吃到高处的树叶，睡觉时间很短',
    secret: '长颈鹿的脖子虽长，颈椎骨数量却和人类一样是七块',
    protectionLevel: '易危',
  },
  {
    id: 20,
    name: '山羊',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/goat.png',
    habitat: '生活在农场和山地牧场',
    food: '什么都爱啃，青草、树叶和杂草都不放过',
    habits: '攀爬本领高超，喜欢站在高处眺望',
    secret: '山羊的瞳孔是长方形的，视野范围能达到三百多度',
    protectionLevel: '家养动物',
  },
  {
    id: 21,
    name: '河马',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/hippopotamus.png',
    habitat: '生活在非洲的河流、湖泊里',
    food: '主要在夜间上岸吃青草',
    habits: '白天大部分时间泡在水里，只露出眼睛和鼻孔',
    secret: '河马的皮肤会分泌天然“防晒油”，呈粉红色',
    protectionLevel: '易危',
  },
  {
    id: 22,
    name: '马',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/horse.png',
    habitat: '生活在草原和农场，是人类重要的伙伴',
    food: '主要吃青草、干草和谷物',
    habits: '站着也能睡觉，奔跑速度快，喜欢群居',
    secret: '马的视野接近350度，几乎能看到身后的情况',
    protectionLevel: '家养动物',
  },
  {
    id: 23,
    name: '鬣狗',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/hyena.png',
    habitat: '生活在非洲的草原和稀树草原',
    food: '既捕猎也吃腐肉，是草原上的“清道夫”',
    habits: '群居生活，笑声般的叫声是它们沟通的方式',
    secret: '鬣狗的咬合力超强，能咬碎坚硬的骨头',
    protectionLevel: '无危',
  },
  {
    id: 24,
    name: '豹',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/leopard.png',
    habitat: '生活在森林、草原甚至山地，适应力极强',
    food: '捕食羚羊、野猪等中小型哺乳动物',
    habits: '擅长爬树，常把猎物拖到树上享用',
    secret: '豹的身手极为敏捷，跳跃距离能达到六米远',
    protectionLevel: '易危',
  },
  {
    id: 25,
    name: '狮子',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/lion.png',
    habitat: '生活在非洲的草原上，是唯一群居的猫科动物',
    food: '主要捕食斑马、角马等大型草食动物',
    habits: '雄狮负责守卫领地，雌狮则是狩猎的主力',
    secret: '狮子的吼声非常洪亮，八公里外都能听到',
    protectionLevel: '易危',
  },
  {
    id: 26,
    name: '蜥蜴',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/lizard.png',
    habitat: '生活在沙漠、森林和草丛等各种环境中',
    food: '主要捕食昆虫，也吃些植物嫩叶',
    habits: '喜欢晒太阳取暖，遇到危险会断尾逃生',
    secret: '蜥蜴断掉的尾巴过一段时间还能重新长出来',
    protectionLevel: '无危',
  },
  {
    id: 27,
    name: '猴子',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/monkey.png',
    habitat: '生活在热带和亚热带的森林里',
    food: '喜欢吃水果、坚果和嫩叶',
    habits: '喜欢群居，在树枝间灵活地跳跃穿梭',
    secret: '猴子的手和人类一样灵活，能用手指抓握和使用工具',
    protectionLevel: '无危',
  },
  {
    id: 28,
    name: '骡鹿',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/mule_deer.png',
    habitat: '生活在北美洲的山地和灌木丛',
    food: '喜欢吃嫩叶、树枝和野草',
    habits: '一对大耳朵像骡子，跳跃时四脚同时离地',
    secret: '骡鹿受到惊吓时会用一种叫“跳跃步”的方式弹跳逃跑',
    protectionLevel: '无危',
  },
  {
    id: 29,
    name: '水獭',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/otter.png',
    habitat: '生活在河流、湖泊等淡水水域附近',
    food: '主要捕食鱼、虾和贝类',
    habits: '喜欢在水中嬉戏打滚，睡觉时会用海藻缠住身体',
    secret: '水獭常常手拉着手睡觉，防止漂散到不同地方',
    protectionLevel: '近危',
  },
  {
    id: 30,
    name: '猫头鹰',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/owl.png',
    habitat: '栖息在森林、田野和城市公园的树洞里',
    food: '主要捕食老鼠、昆虫等小型动物',
    habits: '昼伏夜出，脑袋能转动270度',
    secret: '猫头鹰的羽毛边缘特殊，飞行时几乎悄无声息',
    protectionLevel: '无危',
  },
  {
    id: 31,
    name: '孔雀',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/peacock.png',
    habitat: '生活在亚洲和非洲的热带森林里',
    food: '喜欢吃种子、昆虫和小型爬行动物',
    habits: '雄孔雀会开屏展示美丽的尾羽来吸引雌孔雀',
    secret: '孔雀开屏时尾羽多达两百多根，上面布满“眼斑”',
    protectionLevel: '无危',
  },
  {
    id: 32,
    name: '企鹅',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/penguin.png',
    habitat: '主要生活在南半球，尤其是南极地区',
    food: '主要捕食鱼、虾和磷虾',
    habits: '不会飞，但游泳本领高强，喜欢成群结队行动',
    secret: '企鹅爸爸妈妈轮流孵蛋，把蛋放在脚背上保暖',
    protectionLevel: '近危',
  },
  {
    id: 33,
    name: '猪',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/pig.png',
    habitat: '生活在农场，是人类饲养的重要家畜',
    food: '食性很杂，谷物、蔬菜和厨余都能吃',
    habits: '其实很爱干净，喜欢用泥巴降温防晒',
    secret: '猪的智商很高，学习能力不输给狗狗',
    protectionLevel: '家养动物',
  },
  {
    id: 34,
    name: '浣熊',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/raccoon.png',
    habitat: '生活在森林、河边，也常出没在城市周边',
    food: '喜欢吃鱼虾、坚果和水果',
    habits: '喜欢在水边“洗”食物，眼睛周围有黑色面罩花纹',
    secret: '浣熊的前爪非常灵巧，能打开瓶盖和门把手',
    protectionLevel: '无危',
  },
  {
    id: 35,
    name: '犀牛',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/rhinoceros.png',
    habitat: '生活在非洲和亚洲的草原与丛林里',
    food: '主要吃草和低矮的灌木叶子',
    habits: '视力较弱但嗅觉灵敏，喜欢在泥潭里打滚降温',
    secret: '犀牛角的成分和人的指甲一样，都是角蛋白',
    protectionLevel: '濒危',
  },
  {
    id: 36,
    name: '公鸡',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/rooster.png',
    habitat: '生活在农场和乡村庭院',
    food: '喜欢啄食谷物、种子和小虫子',
    habits: '每天清晨会打鸣报晓，喜欢守护自己的领地',
    secret: '公鸡打鸣其实和体内的生物钟有关，不只是因为天亮',
    protectionLevel: '家养动物',
  },
  {
    id: 37,
    name: '海豹',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/seal.png',
    habitat: '生活在寒冷海域和沿岸的冰面上',
    food: '主要捕食鱼类和乌贼',
    habits: '在陆地上笨拙爬行，一入水就变得灵活自如',
    secret: '海豹的胡须非常敏感，能感知水中猎物的动静',
    protectionLevel: '无危',
  },
  {
    id: 38,
    name: '鲨鱼',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/shark.png',
    habitat: '生活在世界各大海洋中',
    food: '大多数鲨鱼以鱼类和海洋哺乳动物为食',
    habits: '必须不停游动才能让水流过鳃部呼吸',
    secret: '鲨鱼的牙齿掉了还能再长，一生能换上万颗牙',
    protectionLevel: '易危',
  },
  {
    id: 39,
    name: '羊',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/sheep.png',
    habitat: '生活在牧场和草原，是重要的家畜',
    food: '主要吃青草和干草',
    habits: '喜欢群居，胆小容易受惊',
    secret: '羊的毛一年四季都在生长，剪毛后不影响它继续生长',
    protectionLevel: '家养动物',
  },
  {
    id: 40,
    name: '蛇',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/snake.png',
    habitat: '几乎遍布森林、草原、沙漠等各种环境',
    food: '捕食老鼠、青蛙和小型动物，整只吞下',
    habits: '没有四肢，靠腹部的鳞片贴地滑行前进',
    secret: '蛇会定期蜕皮，让身体持续长大',
    protectionLevel: '无危',
  },
  {
    id: 41,
    name: '老虎',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/tiger.png',
    habitat: '生活在森林和丛林中，是独居的猛兽',
    food: '主要捕食鹿、野猪等大型哺乳动物',
    habits: '喜欢在水中降温，领地意识非常强',
    secret: '每只老虎的条纹都独一无二，就像人类的指纹',
    protectionLevel: '濒危',
  },
  {
    id: 42,
    name: '鲸鱼',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/whale.png',
    habitat: '生活在世界各大海洋中',
    food: '须鲸主要滤食磷虾，齿鲸捕食鱼类和乌贼',
    habits: '需要定时浮出水面换气，喜欢用歌声交流',
    secret: '蓝鲸是地球上现存最大的动物，心脏和小汽车一样大',
    protectionLevel: '濒危',
  },
  {
    id: 43,
    name: '狼',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/wolf.png',
    habitat: '生活在森林、草原和苔原等多种环境',
    food: '主要捕食鹿、野兔等中大型哺乳动物',
    habits: '群居生活，团队协作捕猎，等级分明',
    secret: '狼群靠嚎叫互相联络，声音能传出好几公里',
    protectionLevel: '无危',
  },
  {
    id: 44,
    name: '啄木鸟',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/woodpecker.png',
    habitat: '生活在森林里，喜欢在树干上活动',
    food: '主要啄食藏在树皮下的害虫幼虫',
    habits: '用尖尖的喙敲击树干，寻找害虫和挖洞筑巢',
    secret: '啄木鸟的头骨里有海绵状结构，敲树时不会震伤大脑',
    protectionLevel: '无危',
  },
  {
    id: 45,
    name: '斑马',
    image: 'https://tt3ccf4a72a2ab53a201-env-a22yxzsttq.tos-cn-beijing.volces.com/learn/animal/image/zebra.png',
    habitat: '生活在非洲东部和南部的草原上',
    food: '主要吃青草，偶尔吃些树叶和树皮',
    habits: '喜欢群居迁徙，用条纹互相辨认同伴',
    secret: '每匹斑马的条纹图案都不同，就像专属身份证',
    protectionLevel: '近危',
  },
]

async function seedCollection(collectionName, data) {
  const collection = db.collection(collectionName)
  const batchSize = 100
  let added = 0
  let updated = 0

  // 先清空集合（可选：如果想保留历史数据，可以注释掉这段）
  const oldData = await collection.limit(1000).get()
  if (oldData.data.length > 0) {
    const removeTasks = oldData.data.map((item) =>
      collection.doc(item._id).remove()
    )
    await Promise.all(removeTasks)
  }

  // 分批写入
  for (let i = 0; i < data.length; i += batchSize) {
    const batch = data.slice(i, i + batchSize)
    const addTasks = batch.map((item) =>
      collection.add({
        data: {
          ...item,
          createdAt: db.serverDate(),
          updatedAt: db.serverDate(),
        },
      })
    )
    const results = await Promise.all(addTasks)
    added += results.length
  }

  return { added, updated }
}

exports.main = async (event, context) => {
  try {
    const { type = 'all' } = event
    const results = {}

    if (type === 'all' || type === 'terrain') {
      results.terrain = await seedCollection('terrain', terrainData)
    }
    if (type === 'all' || type === 'climate') {
      results.climate = await seedCollection('climate', climateData)
    }
    if (type === 'all' || type === 'animal') {
      results.animal = await seedCollection('animal', animalData)
    }
    if (type === 'all' || type === 'region') {
      results.region = await seedCollection('region', regionData)
    }

    return {
      code: 0,
      msg: '',
      data: results,
    }
  } catch (err) {
    return {
      code: -1,
      msg: err.message,
      data: null,
    }
  }
}
